import Head from "next/head";
import Container from "../components/Container";
import Hero from "../components/Hero";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Emplopedia</title>
        <meta name="description" content="Generated by Towebia" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <div className="flex justify-center mt-10 mb-20">
          <h1 className="flext justify-center text-xl font-bold leading-snug tracking-tight text-gray-800 lg:text-4xl lg:leading-tight xl:text-6xl xl:leading-tight">
            Coming Soon ...
          </h1>
        </div>
        <Hero />
      </Container>
    </div>
  );
}
